# Site settings
title: ferdi265.blog()
email: theferdi265@gmail.com
permalink: pretty
description: >
  I'm Ferdinand "Ferdi265" Bachmann and this is my DevBlog where I post about my recent programming projects.
baseurl: ""
url: "http://ferdi265.github.io"
twitter_username: theFerdi265
github_username:  Ferdi265
disqusid: 3372890

# Markdown settings
markdown: redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
